//! Compile-time GIF -> SSD1309 frame converter.
//!
//! Reads `assets/movie.gif`, stretches every frame to 128x64, applies 8x8 Bayer
//! ordered dithering to 1-bit, packs into the SSD1309 page layout, and emits:
//!   * `$OUT_DIR/frames.bin` - concatenated 1024-byte frames
//!   * `$OUT_DIR/meta.rs`    - FORMAT / FRAME_COUNT / FRAME_DELAYS_MS / dimensions
//!
//! It also runs `embuild::espidf::sysenv::output()` so the ESP-IDF link step
//! still works - the GIF pipeline and the IDF wiring share this one build script.

use std::env;
use std::fs;
use std::io::{BufReader, Write};
use std::path::Path;

use image::codecs::gif::GifDecoder;
use image::imageops::FilterType;
use image::{AnimationDecoder, DynamicImage};

const WIDTH: u32 = 128;
const HEIGHT: u32 = 64;
const FRAME_BYTES: usize = (WIDTH as usize * HEIGHT as usize) / 8; // 1024
const MIN_DELAY_MS: u16 = 30;

/// 8x8 Bayer ordered-dither matrix (values 0..=63). Stable per pixel position,
/// so static regions of the movie do not shimmer between frames.
const BAYER8: [[u8; 8]; 8] = [
    [0, 32, 8, 40, 2, 34, 10, 42],
    [48, 16, 56, 24, 50, 18, 58, 26],
    [12, 44, 4, 36, 14, 46, 6, 38],
    [60, 28, 52, 20, 62, 30, 54, 22],
    [3, 35, 11, 43, 1, 33, 9, 41],
    [51, 19, 59, 27, 49, 17, 57, 25],
    [15, 47, 7, 39, 13, 45, 5, 37],
    [63, 31, 55, 23, 61, 29, 53, 21],
];

fn main() {
    convert_gif();
    // ESP-IDF linker / sysenv setup - required for the device build to link.
    embuild::espidf::sysenv::output();
}

fn convert_gif() {
    let manifest = env::var("CARGO_MANIFEST_DIR").unwrap();
    let gif_path = Path::new(&manifest).join("assets/movie.gif");
    println!("cargo:rerun-if-changed={}", gif_path.display());

    let file = fs::File::open(&gif_path)
        .unwrap_or_else(|e| panic!("cannot open {}: {e}", gif_path.display()));
    let decoder =
        GifDecoder::new(BufReader::new(file)).expect("failed to create GIF decoder");
    let frames = decoder
        .into_frames()
        .collect_frames()
        .expect("failed to decode GIF frames");
    assert!(!frames.is_empty(), "GIF contains no frames");

    let mut blob: Vec<u8> = Vec::with_capacity(frames.len() * FRAME_BYTES);
    let mut delays: Vec<u16> = Vec::with_capacity(frames.len());

    for frame in &frames {
        let (num, den) = frame.delay().numer_denom_ms();
        let ms = if den == 0 { 100 } else { num / den };
        delays.push((ms as u16).max(MIN_DELAY_MS));

        // Stretch to exactly 128x64, then reduce to luma.
        let luma = DynamicImage::ImageRgba8(frame.buffer().clone())
            .resize_exact(WIDTH, HEIGHT, FilterType::Triangle)
            .to_luma8();

        // Bayer-dither into the SSD1309 page layout: byte = 8 vertically stacked
        // pixels, bit 0 = topmost row of the page.
        let mut packed = vec![0u8; FRAME_BYTES];
        for y in 0..HEIGHT {
            for x in 0..WIDTH {
                let lum = luma.get_pixel(x, y).0[0] as u16;
                let threshold = BAYER8[(y % 8) as usize][(x % 8) as usize] as u16 * 4;
                if lum > threshold {
                    let page = (y / 8) as usize;
                    let bit = y % 8;
                    packed[page * WIDTH as usize + x as usize] |= 1 << bit;
                }
            }
        }
        blob.extend_from_slice(&packed);
    }

    let out_dir = env::var("OUT_DIR").unwrap();
    fs::write(Path::new(&out_dir).join("frames.bin"), &blob).unwrap();

    let mut meta = fs::File::create(Path::new(&out_dir).join("meta.rs")).unwrap();
    writeln!(meta, "// Auto-generated by build.rs - do not edit.").unwrap();
    writeln!(meta, "/// Frame encoding: 0 = raw page-packed. Reserved for delta+RLE.").unwrap();
    writeln!(meta, "pub const FORMAT: u8 = 0;").unwrap();
    writeln!(meta, "pub const WIDTH: usize = {WIDTH};").unwrap();
    writeln!(meta, "pub const HEIGHT: usize = {HEIGHT};").unwrap();
    writeln!(meta, "pub const FRAME_BYTES: usize = {FRAME_BYTES};").unwrap();
    writeln!(meta, "pub const FRAME_COUNT: usize = {};", frames.len()).unwrap();
    write!(meta, "pub const FRAME_DELAYS_MS: [u16; {}] = [", delays.len()).unwrap();
    for d in &delays {
        write!(meta, "{d},").unwrap();
    }
    writeln!(meta, "];").unwrap();

    println!(
        "cargo:warning=movie: {} frames, {} bytes total",
        frames.len(),
        blob.len()
    );
}
