//! justicetattoo - plays a compile-time-converted GIF on an SSD1309 OLED.
//!
//! Wiring (ESP32 DevKit V1 -> Waveshare 1.51" transparent OLED, 4-wire SPI):
//!   CLK/SCK = GPIO18   DIN/MOSI = GPIO23   CS = GPIO5   DC = GPIO16   RST = GPIO17
//!   VCC = 3V3          GND = GND
//!
//! The movie frames are generated by `build.rs` from `assets/movie.gif` and
//! embedded into the firmware image - see the `movie` module below.

mod ssd1309;

use esp_idf_svc::hal::delay::{Ets, FreeRtos};
use esp_idf_svc::hal::gpio::{AnyIOPin, PinDriver};
use esp_idf_svc::hal::peripherals::Peripherals;
use esp_idf_svc::hal::prelude::*;
use esp_idf_svc::hal::spi::{config::Config, SpiDeviceDriver, SpiDriver, SpiDriverConfig};

use ssd1309::Ssd1309;

/// Frame data generated at compile time by `build.rs`.
#[allow(dead_code)] // FORMAT/WIDTH/HEIGHT are reserved metadata, not all consumed yet
mod movie {
    include!(concat!(env!("OUT_DIR"), "/meta.rs"));
    /// Concatenated page-packed frames, `FRAME_BYTES` each, living in flash.
    pub static FRAMES: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/frames.bin"));
}

fn main() -> anyhow::Result<()> {
    esp_idf_svc::sys::link_patches();
    esp_idf_svc::log::EspLogger::initialize_default();
    log::info!(
        "justicetattoo: {} frames x {} bytes",
        movie::FRAME_COUNT,
        movie::FRAME_BYTES
    );

    let peripherals = Peripherals::take()?;
    let pins = peripherals.pins;

    // VSPI (spi2): SCLK = GPIO18, MOSI/SDO = GPIO23, no MISO line.
    let spi_driver = SpiDriver::new(
        peripherals.spi2,
        pins.gpio18,
        pins.gpio23,
        None::<AnyIOPin>,
        &SpiDriverConfig::new(),
    )?;
    let config = Config::new().baudrate(10.MHz().into());
    let spi = SpiDeviceDriver::new(spi_driver, Some(pins.gpio5), &config)?;

    let dc = PinDriver::output(pins.gpio16)?;
    let rst = PinDriver::output(pins.gpio17)?;

    let mut display = Ssd1309::new(spi, dc, rst);
    display.init(&mut Ets)?;
    log::info!("display initialised; starting playback loop");

    loop {
        for i in 0..movie::FRAME_COUNT {
            display.blit(decode_frame(i))?;
            FreeRtos::delay_ms(movie::FRAME_DELAYS_MS[i] as u32);
        }
    }
}

/// Returns the page-packed framebuffer for frame `i`.
///
/// `FORMAT == 0` is the raw layout, so this is a direct slice into flash. It is
/// the seam for future delta+RLE: a non-zero `FORMAT` would decode into a
/// reusable RAM buffer here instead of slicing.
fn decode_frame(i: usize) -> &'static [u8] {
    let start = i * movie::FRAME_BYTES;
    &movie::FRAMES[start..start + movie::FRAME_BYTES]
}
