//! justicetattoo - plays a compile-time-converted GIF on an SSD1309 OLED.
//!
//! Wiring (ESP32 DevKit V1 -> Waveshare 1.51" transparent OLED, 4-wire SPI):
//!   CLK/SCK = GPIO18   DIN/MOSI = GPIO23   CS = GPIO5   DC = GPIO16   RST = GPIO17
//!   VCC = 3V3          GND = GND
//!
//! Movie frames are generated by `build.rs` from `assets/movie.gif` and stored
//! either raw or XOR-delta + RLE compressed (`movie::FORMAT`). Both formats are
//! decoded into one reusable framebuffer here - see `render_frame`.

mod ssd1309;

use esp_idf_svc::hal::delay::{Ets, FreeRtos};
use esp_idf_svc::hal::gpio::{AnyIOPin, PinDriver};
use esp_idf_svc::hal::peripherals::Peripherals;
use esp_idf_svc::hal::prelude::*;
use esp_idf_svc::hal::spi::{config::Config, SpiDeviceDriver, SpiDriver, SpiDriverConfig};

use ssd1309::Ssd1309;

/// Frame data generated at compile time by `build.rs`.
#[allow(dead_code)] // WIDTH / HEIGHT are informational metadata
mod movie {
    include!(concat!(env!("OUT_DIR"), "/meta.rs"));
    /// Frame blobs back to back; frame `i` spans `FRAME_OFFSETS[i]..[i + 1]`.
    pub static FRAMES: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/frames.bin"));
}

fn main() -> anyhow::Result<()> {
    esp_idf_svc::sys::link_patches();
    esp_idf_svc::log::EspLogger::initialize_default();
    log::info!(
        "justicetattoo: {} frames, FORMAT={}, {} bytes packed",
        movie::FRAME_COUNT,
        movie::FORMAT,
        movie::FRAMES.len(),
    );

    let peripherals = Peripherals::take()?;
    let pins = peripherals.pins;

    // VSPI (spi2): SCLK = GPIO18, MOSI/SDO = GPIO23, no MISO line.
    let spi_driver = SpiDriver::new(
        peripherals.spi2,
        pins.gpio18,
        pins.gpio23,
        None::<AnyIOPin>,
        &SpiDriverConfig::new(),
    )?;
    let config = Config::new().baudrate(10.MHz().into());
    let spi = SpiDeviceDriver::new(spi_driver, Some(pins.gpio5), &config)?;

    let dc = PinDriver::output(pins.gpio16)?;
    let rst = PinDriver::output(pins.gpio17)?;

    let mut display = Ssd1309::new(spi, dc, rst);
    display.init(&mut Ets)?;
    log::info!("display initialised; starting playback loop");

    // One reusable framebuffer: raw frames are copied in; delta frames are
    // decoded into it in place, so it carries the running state across frames.
    let mut framebuf = [0u8; movie::FRAME_BYTES];
    loop {
        for i in 0..movie::FRAME_COUNT {
            render_frame(i, &mut framebuf);
            display.blit(&framebuf)?;
            FreeRtos::delay_ms(movie::FRAME_DELAYS_MS[i] as u32);
        }
    }
}

/// Render frame `i` into `buf`, handling either storage format.
fn render_frame(i: usize, buf: &mut [u8; movie::FRAME_BYTES]) {
    let blob = &movie::FRAMES
        [movie::FRAME_OFFSETS[i] as usize..movie::FRAME_OFFSETS[i + 1] as usize];
    match movie::FORMAT {
        // Raw: the blob is the verbatim page-packed framebuffer.
        0 => buf.copy_from_slice(blob),
        // XOR-delta + RLE: frame 0 is a delta against zero, so the running
        // buffer is reset at the start of every loop; later frames build on it.
        1 => {
            if i == 0 {
                buf.fill(0);
            }
            apply_delta_rle(blob, buf);
        }
        _ => unreachable!("unknown movie::FORMAT"),
    }
}

/// Apply one RLE-encoded XOR delta to `buf` in place.
///
/// The op stream is 2-byte little-endian headers: bit 15 = type (0 = COPY of an
/// unchanged run, 1 = XOR of a literal run), bits 0..14 = run length. XOR ops
/// are followed by `len` literal bytes that are XORed into `buf`. The length
/// clamps guard against a malformed blob - well-formed data never triggers them.
fn apply_delta_rle(blob: &[u8], buf: &mut [u8]) {
    let mut ip = 0;
    let mut pos = 0;
    while ip + 2 <= blob.len() && pos < buf.len() {
        let header = u16::from_le_bytes([blob[ip], blob[ip + 1]]);
        ip += 2;
        let is_xor = header & 0x8000 != 0;
        let mut len = ((header & 0x7FFF) as usize).min(buf.len() - pos);
        if is_xor {
            len = len.min(blob.len() - ip);
            for k in 0..len {
                buf[pos + k] ^= blob[ip + k];
            }
            ip += len;
        }
        pos += len;
    }
}
